This notebook is intended for class balancing (main disorder and specific disorder) using CTGAN, based on the dataset by Park et al. (2021).

## | Importing libraries

In [1]:
!pip install -q ctgan;
# !pip install -q table_evaluator;
!pip install sdmetrics;

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.3/69.3 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 30.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 77.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 61.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pylibcugraph-cu12 24.12.0 requires pylibraft-cu12==24.12.*, but you have pylibraft-cu12 25.2.0 which is incompatible.
pylibcugraph-cu12 24.12.0 requires rmm-cu12==24.12.*, but you have rmm-cu12 25.2.0 which is incompatible.
Collecting sdmetrics
  Downloading sdmetrics-0.20.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.11/dist-packages (from sdmetrics) (1.26.4)
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from sdmetrics) (2.2.3)
Requirement already satisfied: scikit-learn>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from sdmetrics) (1.2.2)
Requirement already satisfied: scipy>=1.9.2 in /usr/local/lib/python3.11/dist-packages (from sdmetrics) (1.15.2)
Collecting copulas>=0.12.1 (from sdmetrics)
  Downloading copulas-0.12.2-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.11/dist-packages (from sdmetrics) (4.67.1)
Requirement already satisfied: plotly>=5.19.0 in /usr/local/lib/python3.11/dist-packages (from sdmetrics) (5.24.1)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.24.0->sdmetrics) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.24.0->sdmetrics) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.24.0->sdmetrics) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.24.0->sdmetrics) (2025.1.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.24.0->sdmetrics) (2022.1.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.24.0->sdmetrics) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5.0->sdmetrics) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5.0->sdmetrics) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5.0->sdmetrics) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.19.0->sdmetrics) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=5.19.0->sdmetrics) (24.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.1.3->sdmetrics) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.1.3->sdmetrics) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->sdmetrics) (1.17.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.24.0->sdmetrics) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.24.0->sdmetrics) (2022.1.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.24.0->sdmetrics) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.24.0->sdmetrics) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.24.0->sdmetrics) (2024.2.0)
Downloading sdmetrics-0.20.1-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.4/193.4 kB 4.4 MB/s eta 0:00:00
Downloading copulas-0.12.2-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 kB 2.5 MB/s eta 0:00:00
Installing collected packages: copulas, sdmetrics
Successfully installed copulas-0.12.2 sdmetrics-0.20.1

In [2]:
from ctgan import CTGAN
import sdmetrics
from sklearn.impute import KNNImputer
import torch
import pandas as pd
import logging
import time

from warnings import filterwarnings
filterwarnings('ignore')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.init()
torch.zeros(1).cuda()

torch.cuda.is_available(), device, torch.cuda.get_device_name(0)

(True, device(type='cuda'), 'Tesla T4')

## | Dataset

In [3]:
df = pd.read_csv('../input/eeg-psychiatric-disorders-dataset/EEG.machinelearing_data_BRMH.csv')
df

,no.,sex,age,eeg.date,education,IQ,main.disorder,specific.disorder,AB.A.delta.a.FP1,AB.A.delta.b.FP2,...,COH.F.gamma.o.Pz.p.P4,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2
0,1,M,57.0,2012.8.30,NaN,NaN,Addictive disorder,Alcohol use disorder,35.998557,21.717375,...,55.989192,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029
1,2,M,37.0,2012.9.6,6.0,120.0,Addictive disorder,Alcohol use disorder,13.425118,11.002916,...,45.595619,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261
2,3,M,32.0,2012.9.10,16.0,113.0,Addictive disorder,Alcohol use disorder,29.941780,27.544684,...,99.475453,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799
3,4,M,35.0,2012.10.8,18.0,126.0,Addictive disorder,Alcohol use disorder,21.496226,21.846832,...,59.986561,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873
4,5,M,36.0,2012.10.18,16.0,112.0,Addictive disorder,Alcohol use disorder,37.775667,33.607679,...,61.462720,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,941,M,22.0,2014.8.28,13.0,116.0,Healthy control,Healthy control,41.851823,36.771496,...,82.905657,34.850706,63.970519,63.982003,51.244725,62.203684,62.062237,31.013031,31.183413,98.325230
941,942,M,26.0,2014.9.19,13.0,118.0,Healthy control,Healthy control,18.986856,19.401387,...,65.917918,66.700117,44.756285,49.787513,98.905995,54.021304,93.902401,52.740396,92.807331,56.320868
942,943,M,26.0,2014.9.27,16.0,113.0,Healthy control,Healthy control,28.781317,32.369230,...,61.040959,27.632209,45.552852,33.638817,46.690983,19.382928,41.050717,7.045821,41.962451,19.092111
943,944,M,24.0,2014.9.20,13.0,107.0,Healthy control,Healthy control,19.929100,25.196375,...,99.113664,48.328934,41.248470,28.192238,48.665743,42.007147,28.735945,27.176500,27.529522,20.028446
944,945,M,21.0,2015.10.23,13.0,105.0,Healthy control,Healthy control,65.195346,69.241972,...,78.600293,68.255430,70.687410,74.433908,74.294750,53.254681,72.755265,47.810386,80.166825,64.380273

## | Data Cleaning

In [4]:
def remove_missing_columns(df, threshold=0.5):
        limit = int(threshold * len(df))
        df = df.dropna(thresh=limit, axis=1)
        return df

def analyze_missing_values(df):
    missing_values = df.isnull().sum()
    missing_values = missing_values[missing_values > 0]
    total_number_nans = df.isnull().sum().sum()
    
    return missing_values, total_number_nans

def handle_nans(df):
    columns_with_nans = df.columns[df.isnull().any()].tolist()
    
    knn_imputer = KNNImputer(n_neighbors=5, weights='uniform', metric='nan_euclidean')
    
    df_imputed = pd.DataFrame(knn_imputer.fit_transform(df[columns_with_nans]),
                              columns=columns_with_nans)
    
    df[columns_with_nans] = df_imputed[columns_with_nans]

    return df

In [5]:
analyze_missing_values(df)

(education        15
 IQ               13
 Unnamed: 122    945
 dtype: int64,
 973)

In [6]:
df = remove_missing_columns(df)
analyze_missing_values(df)

(education    15
 IQ           13
 dtype: int64,
 28)

In [7]:
df = handle_nans(df)
analyze_missing_values(df)

(Series([], dtype: int64), 0)

In [8]:
df

,no.,sex,age,eeg.date,education,IQ,main.disorder,specific.disorder,AB.A.delta.a.FP1,AB.A.delta.b.FP2,...,COH.F.gamma.o.Pz.p.P4,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2
0,1,M,57.0,2012.8.30,13.43871,101.580472,Addictive disorder,Alcohol use disorder,35.998557,21.717375,...,55.989192,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029
1,2,M,37.0,2012.9.6,6.00000,120.000000,Addictive disorder,Alcohol use disorder,13.425118,11.002916,...,45.595619,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261
2,3,M,32.0,2012.9.10,16.00000,113.000000,Addictive disorder,Alcohol use disorder,29.941780,27.544684,...,99.475453,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799
3,4,M,35.0,2012.10.8,18.00000,126.000000,Addictive disorder,Alcohol use disorder,21.496226,21.846832,...,59.986561,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873
4,5,M,36.0,2012.10.18,16.00000,112.000000,Addictive disorder,Alcohol use disorder,37.775667,33.607679,...,61.462720,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,941,M,22.0,2014.8.28,13.00000,116.000000,Healthy control,Healthy control,41.851823,36.771496,...,82.905657,34.850706,63.970519,63.982003,51.244725,62.203684,62.062237,31.013031,31.183413,98.325230
941,942,M,26.0,2014.9.19,13.00000,118.000000,Healthy control,Healthy control,18.986856,19.401387,...,65.917918,66.700117,44.756285,49.787513,98.905995,54.021304,93.902401,52.740396,92.807331,56.320868
942,943,M,26.0,2014.9.27,16.00000,113.000000,Healthy control,Healthy control,28.781317,32.369230,...,61.040959,27.632209,45.552852,33.638817,46.690983,19.382928,41.050717,7.045821,41.962451,19.092111
943,944,M,24.0,2014.9.20,13.00000,107.000000,Healthy control,Healthy control,19.929100,25.196375,...,99.113664,48.328934,41.248470,28.192238,48.665743,42.007147,28.735945,27.176500,27.529522,20.028446
944,945,M,21.0,2015.10.23,13.00000,105.000000,Healthy control,Healthy control,65.195346,69.241972,...,78.600293,68.255430,70.687410,74.433908,74.294750,53.254681,72.755265,47.810386,80.166825,64.380273

In [9]:
# (19 * 6) + (171 * 6) = 1140

df.iloc[:, 8:]

,AB.A.delta.a.FP1,AB.A.delta.b.FP2,AB.A.delta.c.F7,AB.A.delta.d.F3,AB.A.delta.e.Fz,AB.A.delta.f.F4,AB.A.delta.g.F8,AB.A.delta.h.T3,AB.A.delta.i.C3,AB.A.delta.j.Cz,...,COH.F.gamma.o.Pz.p.P4,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2
0,35.998557,21.717375,21.518280,26.825048,26.611516,25.732649,16.563408,29.891368,22.402246,22.582176,...,55.989192,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029
1,13.425118,11.002916,11.942516,15.272216,14.151570,12.456034,8.436832,9.975238,14.834740,10.950564,...,45.595619,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261
2,29.941780,27.544684,17.150159,23.608960,27.087811,13.541237,16.523963,12.775574,21.686306,18.367666,...,99.475453,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799
3,21.496226,21.846832,17.364316,13.833701,14.100954,13.100939,14.613650,8.063191,11.015078,11.639560,...,59.986561,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873
4,37.775667,33.607679,21.865556,21.771413,22.854536,21.456377,15.969042,9.434306,15.244523,17.041979,...,61.462720,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,41.851823,36.771496,43.671792,36.860889,24.732236,23.607823,23.288260,7.520642,17.636528,20.220791,...,82.905657,34.850706,63.970519,63.982003,51.244725,62.203684,62.062237,31.013031,31.183413,98.325230
941,18.986856,19.401387,27.586436,20.194732,19.407491,20.216570,16.465027,13.178851,12.687296,20.257619,...,65.917918,66.700117,44.756285,49.787513,98.905995,54.021304,93.902401,52.740396,92.807331,56.320868
942,28.781317,32.369230,11.717778,23.134370,26.209302,25.484497,22.586688,11.368466,21.799254,36.083181,...,61.040959,27.632209,45.552852,33.638817,46.690983,19.382928,41.050717,7.045821,41.962451,19.092111
943,19.929100,25.196375,14.445391,16.453456,16.590649,16.007279,18.909188,13.438102,17.442777,18.859586,...,99.113664,48.328934,41.248470,28.192238,48.665743,42.007147,28.735945,27.176500,27.529522,20.028446
944,65.195346,69.241972,35.361363,28.089348,35.475808,36.804968,69.071230,6.905352,22.623165,31.587806,...,78.600293,68.255430,70.687410,74.433908,74.294750,53.254681,72.755265,47.810386,80.166825,64.380273

In [10]:
target = 'specific.disorder'
# label_main = 'Addictive disorder'
label_specific = 'Alcohol use disorder'

df[target]

0      Alcohol use disorder
1      Alcohol use disorder
2      Alcohol use disorder
3      Alcohol use disorder
4      Alcohol use disorder
               ...
940         Healthy control
941         Healthy control
942         Healthy control
943         Healthy control
944         Healthy control
Name: specific.disorder, Length: 945, dtype: object

In [11]:
y = df[target]
X = df.iloc[:,8:]
quantitative_features = df[['age','education', 'IQ']]

X = pd.concat([quantitative_features, X], axis=1)
X

,age,education,IQ,AB.A.delta.a.FP1,AB.A.delta.b.FP2,AB.A.delta.c.F7,AB.A.delta.d.F3,AB.A.delta.e.Fz,AB.A.delta.f.F4,AB.A.delta.g.F8,...,COH.F.gamma.o.Pz.p.P4,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2
0,57.0,13.43871,101.580472,35.998557,21.717375,21.518280,26.825048,26.611516,25.732649,16.563408,...,55.989192,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029
1,37.0,6.00000,120.000000,13.425118,11.002916,11.942516,15.272216,14.151570,12.456034,8.436832,...,45.595619,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261
2,32.0,16.00000,113.000000,29.941780,27.544684,17.150159,23.608960,27.087811,13.541237,16.523963,...,99.475453,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799
3,35.0,18.00000,126.000000,21.496226,21.846832,17.364316,13.833701,14.100954,13.100939,14.613650,...,59.986561,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873
4,36.0,16.00000,112.000000,37.775667,33.607679,21.865556,21.771413,22.854536,21.456377,15.969042,...,61.462720,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,22.0,13.00000,116.000000,41.851823,36.771496,43.671792,36.860889,24.732236,23.607823,23.288260,...,82.905657,34.850706,63.970519,63.982003,51.244725,62.203684,62.062237,31.013031,31.183413,98.325230
941,26.0,13.00000,118.000000,18.986856,19.401387,27.586436,20.194732,19.407491,20.216570,16.465027,...,65.917918,66.700117,44.756285,49.787513,98.905995,54.021304,93.902401,52.740396,92.807331,56.320868
942,26.0,16.00000,113.000000,28.781317,32.369230,11.717778,23.134370,26.209302,25.484497,22.586688,...,61.040959,27.632209,45.552852,33.638817,46.690983,19.382928,41.050717,7.045821,41.962451,19.092111
943,24.0,13.00000,107.000000,19.929100,25.196375,14.445391,16.453456,16.590649,16.007279,18.909188,...,99.113664,48.328934,41.248470,28.192238,48.665743,42.007147,28.735945,27.176500,27.529522,20.028446
944,21.0,13.00000,105.000000,65.195346,69.241972,35.361363,28.089348,35.475808,36.804968,69.071230,...,78.600293,68.255430,70.687410,74.433908,74.294750,53.254681,72.755265,47.810386,80.166825,64.380273

In [12]:
df = pd.concat([X, y], axis=1)
df

,age,education,IQ,AB.A.delta.a.FP1,AB.A.delta.b.FP2,AB.A.delta.c.F7,AB.A.delta.d.F3,AB.A.delta.e.Fz,AB.A.delta.f.F4,AB.A.delta.g.F8,...,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2,specific.disorder
0,57.0,13.43871,101.580472,35.998557,21.717375,21.518280,26.825048,26.611516,25.732649,16.563408,...,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029,Alcohol use disorder
1,37.0,6.00000,120.000000,13.425118,11.002916,11.942516,15.272216,14.151570,12.456034,8.436832,...,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261,Alcohol use disorder
2,32.0,16.00000,113.000000,29.941780,27.544684,17.150159,23.608960,27.087811,13.541237,16.523963,...,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799,Alcohol use disorder
3,35.0,18.00000,126.000000,21.496226,21.846832,17.364316,13.833701,14.100954,13.100939,14.613650,...,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873,Alcohol use disorder
4,36.0,16.00000,112.000000,37.775667,33.607679,21.865556,21.771413,22.854536,21.456377,15.969042,...,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662,Alcohol use disorder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,22.0,13.00000,116.000000,41.851823,36.771496,43.671792,36.860889,24.732236,23.607823,23.288260,...,34.850706,63.970519,63.982003,51.244725,62.203684,62.062237,31.013031,31.183413,98.325230,Healthy control
941,26.0,13.00000,118.000000,18.986856,19.401387,27.586436,20.194732,19.407491,20.216570,16.465027,...,66.700117,44.756285,49.787513,98.905995,54.021304,93.902401,52.740396,92.807331,56.320868,Healthy control
942,26.0,16.00000,113.000000,28.781317,32.369230,11.717778,23.134370,26.209302,25.484497,22.586688,...,27.632209,45.552852,33.638817,46.690983,19.382928,41.050717,7.045821,41.962451,19.092111,Healthy control
943,24.0,13.00000,107.000000,19.929100,25.196375,14.445391,16.453456,16.590649,16.007279,18.909188,...,48.328934,41.248470,28.192238,48.665743,42.007147,28.735945,27.176500,27.529522,20.028446,Healthy control
944,21.0,13.00000,105.000000,65.195346,69.241972,35.361363,28.089348,35.475808,36.804968,69.071230,...,68.255430,70.687410,74.433908,74.294750,53.254681,72.755265,47.810386,80.166825,64.380273,Healthy control

In [13]:
df[target]

0      Alcohol use disorder
1      Alcohol use disorder
2      Alcohol use disorder
3      Alcohol use disorder
4      Alcohol use disorder
               ...
940         Healthy control
941         Healthy control
942         Healthy control
943         Healthy control
944         Healthy control
Name: specific.disorder, Length: 945, dtype: object

In [14]:
class_counts = df[target].value_counts()
max_class_size = class_counts.max()

class_counts, max_class_size

(specific.disorder
 Depressive disorder               199
 Schizophrenia                     117
 Healthy control                    95
 Alcohol use disorder               93
 Behavioral addiction disorder      93
 Bipolar disorder                   67
 Panic disorder                     59
 Posttraumatic stress disorder      52
 Social anxiety disorder            48
 Obsessive compulsitve disorder     46
 Acute stress disorder              38
 Adjustment disorder                38
 Name: count, dtype: int64,
 199)

In [15]:
synthetic_samples = []

In [16]:
df[df[target] == label_specific]

,age,education,IQ,AB.A.delta.a.FP1,AB.A.delta.b.FP2,AB.A.delta.c.F7,AB.A.delta.d.F3,AB.A.delta.e.Fz,AB.A.delta.f.F4,AB.A.delta.g.F8,...,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2,specific.disorder
0,57.00,13.43871,101.580472,35.998557,21.717375,21.518280,26.825048,26.611516,25.732649,16.563408,...,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029,Alcohol use disorder
1,37.00,6.00000,120.000000,13.425118,11.002916,11.942516,15.272216,14.151570,12.456034,8.436832,...,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261,Alcohol use disorder
2,32.00,16.00000,113.000000,29.941780,27.544684,17.150159,23.608960,27.087811,13.541237,16.523963,...,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799,Alcohol use disorder
3,35.00,18.00000,126.000000,21.496226,21.846832,17.364316,13.833701,14.100954,13.100939,14.613650,...,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873,Alcohol use disorder
4,36.00,16.00000,112.000000,37.775667,33.607679,21.865556,21.771413,22.854536,21.456377,15.969042,...,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662,Alcohol use disorder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,37.54,16.00000,111.000000,12.887892,12.811554,11.271938,12.730815,13.449244,13.440774,9.525110,...,59.890110,60.006472,76.000963,76.940229,51.995874,83.445173,29.867826,64.298916,61.308432,Alcohol use disorder
867,41.03,12.00000,94.000000,15.672306,15.865889,14.027073,16.038039,15.950864,15.901984,15.272183,...,42.022839,44.299151,58.055661,65.048325,33.605385,65.283460,24.899975,70.553439,54.170720,Alcohol use disorder
876,54.52,6.00000,68.000000,17.581980,17.776402,13.869724,14.151970,20.869926,18.369719,18.315985,...,48.282117,73.185133,66.742485,49.466312,59.270167,66.639938,40.297206,55.547526,63.630547,Alcohol use disorder
894,49.01,10.00000,106.000000,16.224258,14.015313,10.946295,15.361129,18.104099,13.576599,11.332519,...,30.140302,38.413929,66.371912,60.563340,21.307001,84.886865,9.804814,63.434182,33.162128,Alcohol use disorder
909,22.33,13.00000,76.000000,47.686866,47.886870,42.393642,51.241699,54.177000,49.614786,36.692465,...,34.718710,34.084473,37.717071,62.169600,28.857060,58.361650,12.907714,72.474137,22.491821,Alcohol use disorder

In [17]:
start = time.time()

for label, count in class_counts.items():
    if count < max_class_size:
        print(f"Training for class: {label}")
        
        minority_data = df[df[target] == label]

        ctgan = CTGAN(epochs=300)

        ctgan.fit(minority_data, [target])

        n_to_generate = max_class_size - count
        new_data = ctgan.sample(n_to_generate)

        synthetic_samples.append(new_data)
        
        print(f"Class {label} completed. {n_to_generate} samples generated.")

end = time.time()
elapsed = end - start
print(f"Total training time: {int(elapsed // 60)} min {int(elapsed % 60)} s")

Training for class: Schizophrenia
Class Schizophrenia completed. 82 samples generated.
Training for class: Healthy control
Class Healthy control completed. 104 samples generated.
Training for class: Alcohol use disorder
Class Alcohol use disorder completed. 106 samples generated.
Training for class: Behavioral addiction disorder
Class Behavioral addiction disorder completed. 106 samples generated.
Training for class: Bipolar disorder
Class Bipolar disorder completed. 132 samples generated.
Training for class: Panic disorder
Class Panic disorder completed. 140 samples generated.
Training for class: Posttraumatic stress disorder
Class Posttraumatic stress disorder completed. 147 samples generated.
Training for class: Social anxiety disorder
Class Social anxiety disorder completed. 151 samples generated.
Training for class: Obsessive compulsitve disorder
Class Obsessive compulsitve disorder completed. 153 samples generated.
Training for class: Acute stress disorder
Class Acute stress disorder completed. 161 samples generated.
Training for class: Adjustment disorder
Class Adjustment disorder completed. 161 samples generated.
Total training time: 126 min 8 s

In [18]:
synthetic_samples

[          age  education          IQ  AB.A.delta.a.FP1  AB.A.delta.b.FP2  \
 0   12.486723  12.720248  111.652880          2.725357         21.452343
 1   18.546245  14.794858   91.973729          4.684256         35.090543
 2   13.599379  11.907947  107.347258          9.349618         19.421081
 3   27.346908  12.815714   82.375051         34.597320         50.193828
 4   15.558836  19.125513  108.652151         -1.817344         29.857772
 ..        ...        ...         ...               ...               ...
 77  54.045217  18.654616   77.411420          5.550627         17.067873
 78  29.643875  19.991001   79.396465         20.670457         16.384945
 79  21.986144  12.342485   95.601108         12.705330         19.793787
 80  25.295576  13.538218   90.665064          7.208372         27.622288
 81  14.928677  12.477826   87.374928          7.066886         45.419169

     AB.A.delta.c.F7  AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  \
 0         27.299812        19.019614        25.373663        22.539893
 1         25.702844        21.747822        20.096341         6.902994
 2         31.597079        24.319588        11.128257         1.524109
 3          8.127347        23.540958        30.025157        17.017312
 4         20.471747        24.993812        15.728950        18.494554
 ..              ...              ...              ...              ...
 77        30.656587        24.152795        13.177701         5.332814
 78        20.068006        28.262471        14.079103        10.008582
 79        34.729833        17.725164        14.432459        31.581521
 80        49.018816        12.008629        23.365689        13.910562
 81        38.875651        33.548039        22.636071         8.859649

     AB.A.delta.g.F8  ...  COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  \
 0         14.994883  ...              26.880195              57.820169
 1          9.496179  ...              45.567550              25.359201
 2         10.764051  ...              11.019094              31.597541
 3          0.138230  ...              33.195094               1.373304
 4          2.248556  ...              40.036583              31.316394
 ..              ...  ...                    ...                    ...
 77         5.747482  ...             103.008323              49.642147
 78         8.497076  ...              33.890200              25.921541
 79        18.495773  ...              85.683692              18.048981
 80        25.379591  ...              62.600184              41.193952
 81         1.501785  ...              -9.070575              52.053769

     COH.F.gamma.o.Pz.s.O2  COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  \
 0               72.340303             113.228991              56.707236
 1               81.145683              97.401796               1.298894
 2               48.291539             111.414746              56.116052
 3               56.348701              98.378207              -3.453199
 4               65.225965              62.629056              14.402702
 ..                    ...                    ...                    ...
 77             106.833091              89.205865              53.516458
 78              50.034664             106.613366              40.670256
 79              70.726369             127.294057              47.024109
 80              73.751964             115.334520              42.549333
 81              10.358450             128.157679              67.178884

     COH.F.gamma.p.P4.s.O2  COH.F.gamma.q.T6.r.O1  COH.F.gamma.q.T6.s.O2  \
 0               54.023712               5.539792              38.782711
 1               83.881808              24.405675              13.098263
 2               39.928965              19.604073              24.049729
 3               69.421351              -9.791777               9.909273
 4                5.156964               1.741342              41.310525
 ..                    ...                    ...                    ...
 77              68.019192              70.797185              21.181946
 78              44.748936              15.244929              50.793983
 79              40.694885              -5.580046              16.141648
 80              55.146084              30.284623              30.872243
 81              21.354562               9.916447              50.036462

     COH.F.gamma.r.O1.s.O2  specific.disorder
 0               -5.282597      Schizophrenia
 1               40.959226      Schizophrenia
 2               79.182487      Schizophrenia
 3               83.766819      Schizophrenia
 4               53.742409      Schizophrenia
 ..                    ...                ...
 77              21.925404      Schizophrenia
 78              71.651285      Schizophrenia
 79              23.817563      Schizophrenia
 80              64.278982      Schizophrenia
 81              55.330558      Schizophrenia

 [82 rows x 1144 columns],
            age  education          IQ  AB.A.delta.a.FP1  AB.A.delta.b.FP2  \
 0    22.844753  19.635341  101.577997         -0.158627         12.157265
 1    32.099430  17.366970   99.862723          8.577213        -10.256086
 2    22.782239  11.842604   99.224851         10.329147         25.153469
 3    21.150148  15.969569  102.309960         13.148214          1.153828
 4    35.609453  19.024473   86.166617         21.878403          1.238003
 ..         ...        ...         ...               ...               ...
 99   22.372188  17.430922  113.565981          9.723717         18.164863
 100  28.370759  20.214051  108.480900         14.861885         13.864968
 101  31.593826  16.705216   95.635595         10.305405          6.144893
 102  31.463727  16.231971   92.646521          7.447860         15.204655
 103  35.471727  16.194702   82.579574         14.489085         -0.220448

      AB.A.delta.c.F7  AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  \
 0          15.651066         3.311143         4.586525        11.567900
 1          18.161463        24.017802        11.223251        33.414921
 2           2.524673         6.228727        18.384992        15.315903
 3          12.662685         9.244471        24.414961        11.620902
 4          16.395520         0.785941        60.135301         9.894822
 ..               ...              ...              ...              ...
 99         12.101192         5.961463        10.974179        13.036013
 100        15.381194         5.134753        77.260386        18.687935
 101        16.550523        20.227914        21.388798       -15.649655
 102        10.209904        22.670298        18.492398        21.431309
 103        12.137078         8.764012        33.770992         1.007920

      AB.A.delta.g.F8  ...  COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  \
 0          23.854894  ...              20.244066              48.814662
 1          18.009419  ...              76.498851              28.905340
 2           4.357535  ...              58.463609              87.799399
 3           3.916693  ...              83.427632              24.547438
 4          11.047932  ...              19.183229              86.522840
 ..               ...  ...                    ...                    ...
 99         17.501686  ...              66.924069              16.225603
 100        12.989039  ...              82.192031              48.360674
 101         7.907764  ...             102.522807              24.519347
 102        22.170177  ...              30.136868              74.203911
 103        11.041368  ...              77.916668               4.258650

      COH.F.gamma.o.Pz.s.O2  COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  \
 0                70.452581             101.826748              42.050585
 1                45.868030              68.887237              55.105020
 2                92.800095              74.903923              25.583728
 3                92.565253               8.968537              79.193075
 4                46.469301              78.240621             113.234146
 ..                     ...                    ...                    ...
 99               17.128886              76.104492              53.350696
 100             113.485517              86.173992              71.240865
 101              -4.621093              79.092728              60.175106
 102              43.942259              67.950705              67.991447
 103              84.331102              76.130114              59.749703

      COH.F.gamma.p.P4.s.O2  COH.F.gamma.q.T6.r.O1  COH.F.gamma.q.T6.s.O2  \
 0               106.897248             111.928290              68.437130
 1               106.531298              60.518181              94.790849
 2                82.568591             100.434022             114.497106
 3                -0.619199              13.314310             127.181312
 4                84.115848             112.422870             125.476493
 ..                     ...                    ...                    ...
 99               70.030461              47.471990              82.409552
 100              86.112888              99.968689             112.346783
 101              48.385789               7.823821             116.688336
 102              83.567105              49.198960              98.919410
 103              28.626794              57.244016             111.195515

      COH.F.gamma.r.O1.s.O2  specific.disorder
 0                27.494035    Healthy control
 1                10.432663    Healthy control
 2                 8.343808    Healthy control
 3                66.589362    Healthy control
 4                79.144867    Healthy control
 ..                     ...                ...
 99                7.920968    Healthy control
 100              17.161570    Healthy control
 101              76.612878    Healthy control
 102              -2.606503    Healthy control
 103              31.307414    Healthy control

 [104 rows x 1144 columns],
            age  education          IQ  AB.A.delta.a.FP1  AB.A.delta.b.FP2  \
 0    23.275215  15.661212  113.898751         17.785918         12.186619
 1    35.938413  13.113459   81.166259          1.945130          9.539438
 2    38.292338  14.157874   93.045004         30.196307         15.413339
 3    26.797906   9.500477   89.229642         20.702643          1.016159
 4    32.770050  15.477243   91.925578         13.499599          4.214372
 ..         ...        ...         ...               ...               ...
 101  44.840841  17.626225  110.391468         41.796309         14.215649
 102  19.427961  16.825077  100.369769         20.016178          7.481307
 103  50.302645  14.280128  131.007506          7.818654         20.626444
 104  21.349445  16.922648  141.132815         21.747716         10.023890
 105  16.364965  14.863480   55.826959         34.850105         12.529297

      AB.A.delta.c.F7  AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  \
 0          27.782146         2.032735        73.492876        18.886248
 1          23.553429         1.205643        15.272858         3.776997
 2          22.228630         0.258370        32.357610         7.717407
 3          20.317827         9.759208        28.569793        29.260699
 4          16.588591         3.179746        64.732083         5.899658
 ..               ...              ...              ...              ...
 101        19.645002        24.408619        53.206333         4.754254
 102        15.461563         0.347976        10.786769         0.589782
 103        19.777612        10.194448        31.270615         8.570968
 104        21.017293        -1.481704        36.258645        22.276414
 105        38.658222        17.131041        17.120465         6.751334

      AB.A.delta.g.F8  ...  COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  \
 0           5.998548  ...              33.106059              15.446373
 1          19.918994  ...              50.997456              55.958300
 2          22.131426  ...              61.689496              75.155602
 3          11.620595  ...              -5.466131              77.082251
 4          49.399458  ...             104.135322              63.683507
 ..               ...  ...                    ...                    ...
 101        22.530848  ...              62.799310              86.993114
 102         9.242456  ...              72.606144              47.010943
 103        20.815202  ...              32.547929              53.142517
 104         6.798184  ...              23.616594              46.187393
 105        22.048300  ...              43.503803              94.698926

      COH.F.gamma.o.Pz.s.O2  COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  \
 0                -9.856925              44.556510              62.071665
 1                24.513038              76.064708              24.229859
 2                72.979682             113.570166              21.967211
 3                 2.885179              71.864716              54.057089
 4                39.451781             104.716330             -19.094604
 ..                     ...                    ...                    ...
 101              66.289879              36.581331              74.315921
 102              23.586219              65.365635              13.628138
 103              26.049008              66.338549              35.045045
 104              -6.202860              50.420996              49.918541
 105              21.022174              68.864219              89.423854

      COH.F.gamma.p.P4.s.O2  COH.F.gamma.q.T6.r.O1  COH.F.gamma.q.T6.s.O2  \
 0               101.469251             119.529086              59.518089
 1               103.823753             106.423108              44.627569
 2               121.318715              57.606239              45.022394
 3                82.378224              99.535076             100.489079
 4                84.101437              91.823053              27.120617
 ..                     ...                    ...                    ...
 101              75.557016              21.134842              39.938819
 102              53.258691              70.895946              76.890245
 103              22.146556              64.770290              32.253427
 104             104.515568              45.382557              76.588239
 105              50.289295              80.249304              61.623421

      COH.F.gamma.r.O1.s.O2     specific.disorder
 0                25.886556  Alcohol use disorder
 1                35.847587  Alcohol use disorder
 2                79.013429  Alcohol use disorder
 3                66.485298  Alcohol use disorder
 4                56.342754  Alcohol use disorder
 ..                     ...                   ...
 101              80.483761  Alcohol use disorder
 102              31.475664  Alcohol use disorder
 103              29.703913  Alcohol use disorder
 104              63.350097  Alcohol use disorder
 105              18.975547  Alcohol use disorder

 [106 rows x 1144 columns],
            age  education          IQ  AB.A.delta.a.FP1  AB.A.delta.b.FP2  \
 0    24.996248  12.934919   99.760927         36.683337         13.682015
 1    33.961048  12.613367   77.556452         14.768619         24.306238
 2    32.245505  11.171285  130.607576         27.338957         18.609155
 3    29.130252  11.299942  128.308726          5.630498         20.128729
 4    22.330484  11.675192   78.525626          7.032991          9.332794
 ..         ...        ...         ...               ...               ...
 101  38.889450  14.177746  108.085156          1.727870         21.087177
 102  20.676604  12.125062  132.501834          5.881524         21.058920
 103  19.763860  11.476627  137.450831          4.962406          7.697517
 104  21.659606   6.725070  102.574738         17.238012         22.214988
 105  36.566796  11.537671   97.428503          9.077853         42.610601

      AB.A.delta.c.F7  AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  \
 0          13.989712        17.456195        26.955652         7.385330
 1          18.103591        13.745178        40.653524        11.064052
 2           6.347233         8.821857        16.255795         8.601137
 3          15.165440         6.805670        24.132727        11.975806
 4          19.869392         8.428020        13.524196         9.798029
 ..               ...              ...              ...              ...
 101        16.432340        15.639769        10.454287        11.860290
 102        14.066966        29.874374        25.541962         7.190282
 103        22.006688         9.972185        20.313780         4.323241
 104        12.850533        17.826137        13.982075         6.953622
 105         6.186778         4.599447         9.185522        16.407281

      AB.A.delta.g.F8  ...  COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  \
 0          20.493752  ...              91.377780              73.179948
 1          24.992309  ...             107.847932              97.459117
 2          18.295960  ...             114.444997              72.224647
 3          38.174681  ...              90.665262              13.589649
 4          29.552508  ...              47.807241              52.652454
 ..               ...  ...                    ...                    ...
 101        20.880450  ...             100.851648              67.328798
 102        19.756280  ...              49.274690              46.472086
 103         8.381967  ...              38.321730              54.818216
 104        30.888492  ...              84.985441              52.795537
 105        24.227507  ...              53.386084              47.607585

      COH.F.gamma.o.Pz.s.O2  COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  \
 0                40.665465              43.740831              63.812735
 1                47.429676              78.033781              60.397178
 2                32.660751              67.040077              65.629389
 3                39.045136              99.228435              72.268449
 4                33.746836             101.094824              55.597995
 ..                     ...                    ...                    ...
 101              27.140492              72.908377              21.268712
 102              36.683619              94.053534              81.135380
 103              64.640513              57.475991              38.951148
 104              46.972999              11.288403              50.465518
 105              31.346372              80.526007              92.816244

      COH.F.gamma.p.P4.s.O2  COH.F.gamma.q.T6.r.O1  COH.F.gamma.q.T6.s.O2  \
 0                69.389382              28.397736              28.070478
 1                76.930769              84.926895              24.130722
 2                85.538859              27.268553              72.367306
 3                62.232628              81.616245              50.184919
 4                22.028671              43.348860              43.449028
 ..                     ...                    ...                    ...
 101              50.791436              28.572018              54.897056
 102              83.308785              -2.543283              35.749565
 103              53.940593              47.497678              63.745792
 104              97.139519              46.393352              78.182564
 105              97.146658              56.113450              81.972751

      COH.F.gamma.r.O1.s.O2              specific.disorder
 0                54.214690  Behavioral addiction disorder
 1                74.068317  Behavioral addiction disorder
 2                80.938694  Behavioral addiction disorder
 3                40.011257  Behavioral addiction disorder
 4                31.471041  Behavioral addiction disorder
 ..                     ...                            ...

In [19]:
synthetic_samples = pd.concat(synthetic_samples, ignore_index=True)

In [20]:
synthetic_samples

,age,education,IQ,AB.A.delta.a.FP1,AB.A.delta.b.FP2,AB.A.delta.c.F7,AB.A.delta.d.F3,AB.A.delta.e.Fz,AB.A.delta.f.F4,AB.A.delta.g.F8,...,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2,specific.disorder
0,12.486723,12.720248,111.652880,2.725357,21.452343,27.299812,19.019614,25.373663,22.539893,14.994883,...,26.880195,57.820169,72.340303,113.228991,56.707236,54.023712,5.539792,38.782711,-5.282597,Schizophrenia
1,18.546245,14.794858,91.973729,4.684256,35.090543,25.702844,21.747822,20.096341,6.902994,9.496179,...,45.567550,25.359201,81.145683,97.401796,1.298894,83.881808,24.405675,13.098263,40.959226,Schizophrenia
2,13.599379,11.907947,107.347258,9.349618,19.421081,31.597079,24.319588,11.128257,1.524109,10.764051,...,11.019094,31.597541,48.291539,111.414746,56.116052,39.928965,19.604073,24.049729,79.182487,Schizophrenia
3,27.346908,12.815714,82.375051,34.597320,50.193828,8.127347,23.540958,30.025157,17.017312,0.138230,...,33.195094,1.373304,56.348701,98.378207,-3.453199,69.421351,-9.791777,9.909273,83.766819,Schizophrenia
4,15.558836,19.125513,108.652151,-1.817344,29.857772,20.471747,24.993812,15.728950,18.494554,2.248556,...,40.036583,31.316394,65.225965,62.629056,14.402702,5.156964,1.741342,41.310525,53.742409,Schizophrenia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,41.024158,21.338190,137.508387,3.897484,6.600202,11.625845,13.960831,37.676382,30.945274,11.202927,...,47.175044,25.935223,80.153058,110.550349,58.663091,41.690877,-5.156744,81.195055,2.983596,Adjustment disorder
1439,55.499292,12.990695,80.726012,1.785503,8.328488,30.755002,21.065130,37.601797,26.809310,29.847553,...,58.018386,62.111926,86.762645,62.187134,16.427574,66.377102,18.068607,46.783253,44.923293,Adjustment disorder
1440,56.778344,18.878593,138.331332,19.287896,0.594376,41.444599,41.514412,41.861253,21.975527,26.688986,...,87.730085,66.344053,85.630108,85.603845,1.485398,49.566798,24.463577,111.231455,93.531027,Adjustment disorder
1441,46.136011,15.122581,121.912296,2.706127,25.875806,38.546985,24.760639,8.782951,20.560540,15.400793,...,72.473839,80.167055,86.254430,59.050772,45.043488,80.776484,-13.517152,99.023455,3.971395,Adjustment disorder
1442,33.183874,12.984464,120.547680,13.655639,16.646781,31.093434,20.784400,40.626022,63.503731,18.258908,...,78.344326,109.938131,108.540203,53.452303,-3.917687,54.348445,-9.749098,105.386819,78.966977,Adjustment disorder

In [21]:
class_counts_synth = synthetic_samples[target].value_counts()
max_class_size_synth = class_counts_synth.max()

# [82, 104, 106, 106, 132, 140, 147, 151, 153, 161, 161] = 1.443
class_counts_synth, max_class_size_synth, class_counts_synth.sum()

(specific.disorder
 Acute stress disorder             161
 Adjustment disorder               161
 Obsessive compulsitve disorder    153
 Social anxiety disorder           151
 Posttraumatic stress disorder     147
 Panic disorder                    140
 Bipolar disorder                  132
 Alcohol use disorder              106
 Behavioral addiction disorder     106
 Healthy control                   104
 Schizophrenia                      82
 Name: count, dtype: int64,
 161,
 1443)

In [22]:
synthetic_samples.to_csv('synthetic_samples_specific_disorder_ctgan.csv', index=True)