In [2]:
!pip install mne

In [1]:
import pandas as pd 
import numpy as np
import mne

In [4]:
data = pd.read_csv('/kaggle/input/eeg-psychiatric-disorders-dataset/EEG.machinelearing_data_BRMH.csv')
data.head()

,no.,sex,age,eeg.date,education,IQ,main.disorder,specific.disorder,AB.A.delta.a.FP1,AB.A.delta.b.FP2,...,COH.F.gamma.o.Pz.p.P4,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2
0,1,M,57.0,2012.8.30,NaN,NaN,Addictive disorder,Alcohol use disorder,35.998557,21.717375,...,55.989192,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029
1,2,M,37.0,2012.9.6,6.0,120.0,Addictive disorder,Alcohol use disorder,13.425118,11.002916,...,45.595619,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261
2,3,M,32.0,2012.9.10,16.0,113.0,Addictive disorder,Alcohol use disorder,29.941780,27.544684,...,99.475453,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799
3,4,M,35.0,2012.10.8,18.0,126.0,Addictive disorder,Alcohol use disorder,21.496226,21.846832,...,59.986561,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873
4,5,M,36.0,2012.10.18,16.0,112.0,Addictive disorder,Alcohol use disorder,37.775667,33.607679,...,61.462720,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662

In [17]:
data = data.set_index('no.')

In [20]:
data.iloc[:, :7].head(30)

,sex,age,eeg.date,education,IQ,main.disorder,specific.disorder
no.,,,,,,,
1,M,57.0,2012.8.30,NaN,NaN,Addictive disorder,Alcohol use disorder
2,M,37.0,2012.9.6,6.0,120.0,Addictive disorder,Alcohol use disorder
3,M,32.0,2012.9.10,16.0,113.0,Addictive disorder,Alcohol use disorder
4,M,35.0,2012.10.8,18.0,126.0,Addictive disorder,Alcohol use disorder
5,M,36.0,2012.10.18,16.0,112.0,Addictive disorder,Alcohol use disorder
6,F,24.0,2012.11.21,14.0,105.0,Addictive disorder,Alcohol use disorder
7,F,26.0,2012.12.3,16.0,103.0,Addictive disorder,Alcohol use disorder
8,M,23.0,2013.1.17,12.0,104.0,Addictive disorder,Alcohol use disorder
9,M,24.0,2013.2.15,17.0,89.0,Addictive disorder,Alcohol use disorder
10,F,30.0,2013.2.8,12.0,98.0,Addictive disorder,Alcohol use disorder
11,M,34.0,2013.2.18,13.0,91.0,Addictive disorder,Alcohol use disorder
12,M,32.0,2013.3.8,12.0,93.0,Addictive disorder,Alcohol use disorder
13,M,20.0,2013.2.20,13.0,105.0,Addictive disorder,Alcohol use disorder
14,M,28.0,2013.4.15,14.0,118.0,Addictive disorder,Alcohol use disorder
15,M,23.0,2013.4.11,13.0,116.0,Addictive disorder,Alcohol use disorder
16,M,20.0,2013.4.25,12.0,93.0,Addictive disorder,Alcohol use disorder
17,M,26.0,2013.8.29,12.0,107.0,Addictive disorder,Alcohol use disorder
18,M,30.0,2013.9.27,NaN,86.0,Addictive disorder,Alcohol use disorder
19,M,31.0,2013.10.18,18.0,102.0,Addictive disorder,Alcohol use disorder
20,M,25.0,2013.11.20,16.0,120.0,Addictive disorder,Alcohol use disorder
21,M,39.0,2013.12.27,12.0,128.0,Addictive disorder,Alcohol use disorder
22,M,20.0,2014.10.23,NaN,116.0,Addictive disorder,Alcohol use disorder
23,M,30.0,2014.7.7,16.0,102.0,Addictive disorder,Alcohol use disorder
24,M,23.0,2014.7.25,12.0,104.0,Addictive disorder,Alcohol use disorder
25,M,29.0,2014.7.25,13.0,122.0,Addictive disorder,Alcohol use disorder
26,M,32.0,2014.9.19,16.0,130.0,Addictive disorder,Alcohol use disorder
27,M,34.0,2014.9.25,13.0,122.0,Addictive disorder,Alcohol use disorder
28,M,26.0,2014.12.18,17.0,108.0,Addictive disorder,Alcohol use disorder
29,M,25.0,2014.11.24,13.0,117.0,Addictive disorder,Alcohol use disorder
30,M,30.0,2015.11.12,16.0,122.0,Addictive disorder,Alcohol use disorder

In [5]:
data.shape

(945, 1149)

In [ ]:
for col in data.columns.tolist()[7:]:
    print(col)

In [32]:
for i, j in zip(data.isna().sum().index, data.isna().sum()):
    if j != 0:
        print(i, j)

education 15
IQ 13
Unnamed: 122 945